import type { Bucket } from "@/types/bucket";

export const mockBuckets: Bucket[] = [
  {
    id: "1",
    bucketName: "my-backup-bucket",
    region: "us-east-1",
    createdOn: new Date("2024-01-01"),
    size: "2.5 GB",
    numberOfFolders: 12,
    numberOfObjects: 485,
    lastUsed: new Date("2024-11-20"),
    versioningEnabled: true,
    storageClass: "STANDARD",
  },
  {
    id: "2",
    bucketName: "website-assets",
    region: "eu-west-1",
    createdOn: new Date("2024-01-15"),
    size: "1.2 GB",
    numberOfFolders: 8,
    numberOfObjects: 234,
    lastUsed: new Date("2024-11-25"),
    versioningEnabled: false,
    storageClass: "COLD",
  },
  {
    id: "3",
    bucketName: "user-uploads",
    region: "ap-south-1",
    createdOn: new Date("2024-02-01"),
    size: "5.8 GB",
    numberOfFolders: 25,
    numberOfObjects: 1024,
    lastUsed: new Date("2024-11-28"),
    versioningEnabled: true,
    storageClass: "STANDARD",
  },
  {
    id: "4",
    bucketName: "data-analytics",
    region: "us-west-2",
    createdOn: new Date("2024-03-15"),
    size: "12.4 GB",
    numberOfFolders: 35,
    numberOfObjects: 2156,
    lastUsed: new Date("2024-11-30"),
    versioningEnabled: false,
    storageClass: "GLACIER",
  },
  {
    id: "5",
    bucketName: "mobile-app-assets",
    region: "ap-southeast-1",
    createdOn: new Date("2024-04-20"),
    size: "890 MB",
    numberOfFolders: 6,
    numberOfObjects: 145,
    lastUsed: new Date("2024-11-29"),
    versioningEnabled: true,
    storageClass: "STANDARD",
  },
  {
    id: "6",
    bucketName: "log-archive",
    region: "eu-central-1",
    createdOn: new Date("2024-05-10"),
    size: "18.2 GB",
    numberOfFolders: 52,
    numberOfObjects: 3428,
    lastUsed: new Date("2024-11-27"),
    versioningEnabled: false,
    storageClass: "GLACIER",
  },
];
